### ISSUE TITLE
hello-solder doesn't compile with v4

### ISSUE THREAD

**Issue by nocko** [boldport/pcbmode#14]
Trying to work my way through documentation / tutorial; but it appears that the hello-solder no longer compiles with v4. utils.modules:Module._getComponents is called on the config.brd['shapes'] and it appears that pcbmode now expects each shape to have a refdef and be a dict like components; hello-solder.json has a different structure.

**Comment by saardrimer** [comment]
Yes, hello-solder was for v3. Documentation is hit-and-miss... I try to maintain comparability notes in the README of each board repo, but...
