### ISSUE TITLE
via extraction doesn't set the "assembly" or "silkscreen" labels to not show

### ISSUE THREAD

**Issue by peterfillmore** [boldport/pcbmode#16]
This means that via designators are printed in the silkscreen layer.
fixed it in my case by adding (last two lines)

`vias_dict[digest] = {}`
 `vias_dict[digest]['footprint'] = marker.get('{'+config.cfg['ns']['pcbmode']+'}footprint')`
 `vias_dict[digest]['location'] = [utils.niceFloat(location.x),
                                             utils.niceFloat(location.y)]`
 `vias_dict[digest]['layer'] = 'top'`
 `vias_dict[digest]['silkscreen'] = {'refdef':{'show':False}}`
 `vias_dict[digest]['assembly'] = {'refdef':{'show':False}}`

**Comment by saardrimer** [comment]
Fixed!
