### ISSUE TITLE
cannot perform relative import

### ISSUE THREAD

**Issue by paulbiggins** [boldport/pcbmode#18]
having a lot of problems with relative import when trying to run pcbmode.py

```
[paul@trunks pcbmode]# python pcbmode/pcbmode.py
Traceback (most recent call last):
   File "pcbmode/pcbmode.py", line 15, in <module>
      from . import config
SystemError: Parent module '' not loaded, cannot perform relative import
```

tested using python3 and python2 on linux. also tested using python2 on OSX.

**Comment by saardrimer** [comment]
Have you looked at the pending pull request from @nocko with documentation? I'm really behind sorting this out. Sorry!

**Comment by paulbiggins** [comment]
Oh okay. That works! Awesome!
