### ISSUE TITLE
gerber-lp ? 

### ISSUE THREAD

**Issue by rahji** [boldport/pcbmode#31]
Can you explain the gerber-lp attribute? I see it in the examples, but I can't find any mention of it in the documentation or in comments. Thanks.

**Comment by JarrettR** [comment]
Based on this chunk of code:
https://github.com/boldport/pcbmode/blob/3b3d7471ba2098ba9571846f0a0ea4b747c661d1/pcbmode/utils/gerber.py#L346

It appears to add a gerber command `LP`, which is described on page 128 of this document:
https://www.ucamco.com/files/downloads/file/81/the_gerber_file_format_specification.pdf

So this sets the polarity mode of the shape. Basically a series of boolean addition and subtraction operations, it looks like. That document provides some examples, too.
