### ISSUE TITLE
units of components

### ISSUE THREAD

**Issue by rimmartin** [boldport/pcbmode#34]
Hi,

If a psbmode json is made from translating another format and the units are say milimeter, is there a way to say that component' units so the output agrees?

**Comment by saardrimer** [comment]
I'm not sure I fully understand your question. PCBmodE was always meant to support multiple units, but I never implemented that. So in reality all measurements are interpreted as 'mm'.

**Comment by rimmartin** [comment]
I made a translator from bxl to your json.  Albeit it is in different units. I can make the conversion

**Comment by saardrimer** [comment]
Oh, I see. I missed that part. Yeah, at the moment PCBmodE will only accept mm.

**Comment by WayneKeenan** [comment]
@rimmartin did you ever publish the BXL to JSON translator?
