### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Immortalin** [boldport/pcbmode#48]
Any plans for python 3 support?

**Comment by JarrettR** [comment]
The dev fork works fine in Python 3:

https://github.com/threebytesfull/pcbmode/tree/develop

**Comment by Immortalin** [comment]
@JarrettR unable to get [`hello-solder`](https://github.com/boldport/hello-solder) working on fork, any suggestions for other example boards?

**Comment by JarrettR** [comment]
Yeah, that one is for an older version. [Thelady ](https://github.com/boldport/thelady) is a complicated one that works.

I like [Binco](https://github.com/boldport/binco), a lot less stuff to strip out as an example project.

**Comment by saardrimer** [comment]
I'm starting to work on the next version of PCBmodE at branch `cinco-master`. We'll drop support for Python2 and require Python 3.7+.

**Comment by Neon22** [comment]
Please just use the highest python that inkscape is using. not sure if its going to be 3.7 or 3.5 ???

**Comment by saardrimer** [comment]
It's not explicitly stated... if it's using what's available on the system it'd launch which Python3 you're already using for PCBmodE. Right?

https://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0

**Comment by Neon22** [comment]
They bundle a version with the install so they can control the version used by all of the extensions and includes TlInter as a UI. I think they have not decided for sure yet which version they will bundle with 1.0 but I'd have to check the dev email list.
in 0.48 it was a really old version of python. in 0.92 they finally updated it and for 1.0 they will log to Python 3.

**Comment by saardrimer** [comment]
Ah. OK. It would be great to know.

**Comment by Neon22** [comment]
https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#For_extension_writers

3.7 I surmise
