### ISSUE TITLE
Getting Started doc link to the ‘boards’ repo is HTTP 404

### ISSUE THREAD

**Issue by WayneKeenan** [boldport/pcbmode#55]
The documentation has a link to an example ‘boards’ GitHub repo that is no longer there.

A n00b to PCBmodE may find this to be a road block.

**Comment by JarrettR** [comment]
See also issue #14 and #29

**Comment by JarrettR** [comment]
Also see PR #46 that should be merged in!

**Comment by WayneKeenan** [comment]
Ok, but it’s a bit of time consuming leg work to find top level repos that work.

A single repo with a bunch of known good working examples (ideally in step with mainline) is always a plus for any project.

I’m sure I’m talking to the converted, apologies I can’t help much more at this stage.

I’m really not trying to complain.
